spring.application.name=uco-parking

server.port=8081

# Conexion
spring.datasource.url=jdbc:postgresql://localhost:5432/uco_parking26
spring.datasource.username=postgres
spring.datasource.password=Danilo980521

# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect